package com.mazawrath.beanbot.utilities.Pokebean.Monster;

public enum Ability
{
    ADAPTABILITY("Powers up moves of the same type."),
    AFTERMATH("Damages the foe landing the finishing hit."),
    AIR_LOCK("Eliminates the effects of weather."),
    ANALYTIC("Strengthens moves when moving last."),
    ANGER_POINT("Raises Attack upon taking a critical hit."),
    ANTICIPATION("Senses the foe’s dangerous moves."),
    ARENA_TRAP("Prevents the foe from fleeing."),
    BAD_DREAMS("Reduces a sleeping foe’s HP."),
    BATTLE_ARMOR("The Pokebean is protected against critical hits."),
    BIG_PECKS("Protects the Pokebean from Defense-lowering attacks."),
    BLAZE("Powers up Fire-type moves in a pinch."),
    CACOPHONY("Avoids sound-based moves."),
    CHLOROPHYLL("Boosts the Pokebean’s Speed in sunshine."),
    CLEAR_BODY("Prevents the Pokebean’s stats from being lowered."),
    CLOUD_NINE("Eliminates the effects of weather."),
    COLOR_CHANGE("Changes the Pokebean’s type to the foe’s move."),
    COMPOUNDEYES("The Pokebean’s accuracy is boosted."),
    CONTRARY("Inverts stat modifiers."),
    CURSED_BODY("Has a 30% chance of Disabling any move that hits the Pokebean."),
    CUTE_CHARM("Contact with the Pokebean may cause infatuation."),
    DAMP("Prevents combatants from self destructing."),
    DEFEATIST("Halves Attack and Special Attack below 50% HP."),
    DEFIANT("Raises Attack two stages upon having any stat lowered."),
    DOWNLOAD("Adjusts power according to the foe’s lowest defensive stat."),
    DRIZZLE("The Pokebean makes it rain if it appears in battle."),
    DROUGHT("The Pokebean makes it sunny if it is in battle."),
    DRY_SKIN("Reduces HP if it is hot. Water restores HP."),
    EARLY_BIRD("The Pokebean awakens quickly from sleep."),
    EFFECT_SPORE("Contact may paralyze, poison, or cause sleep."),
    FILTER("Powers down super-effective moves."),
    FLAME_BODY("Contact with the Pokebean may burn the foe."),
    FLARE_BOOST("Increases Special Attack to 1.5× when burned."),
    FLASH_FIRE("Powers up Fire-type moves if hit by a fire move."),
    FLOWER_GIFT("Powers up party Pokebean when it is sunny."),
    FORECAST("Transforms with the weather."),
    FOREWARN("Determines what moves the foe has."),
    FRIEND_GUARD("Decreases damage inflicted against ally Pokebean."),
    FRISK("The Pokebean can check the foe’s held item."),
    GLUTTONY("Encourages the early use of a held Berry."),
    GUTS("Boosts Attack if there is a status problem."),
    HARVEST("Restores any held Berry after the turn on which it is used."),
    HEALER("Has a 30% chance of curing each adjacent ally of any major status ailment after each turn."),
    HEATPROOF("Weakens the power of Fire-type moves."),
    HEAVY_METAL("Doubles the Pokebean's weight."),
    HONEY_GATHER("The Pokebean may gather Honey from somewhere."),
    HUGE_POWER("Raises the Pokebean’s Attack stat."),
    HUSTLE("Boosts the Attack stat, but lowers accuracy."),
    HYDRATION("Heals status problems if it is raining."),
    HYPER_CUTTER("Prevents the Attack stat from being lowered."),
    ICE_BODY("The Pokebean regains HP in a hailstorm."),
    ILLUMINATE("Raises the likelihood of meeting wild Pokebean."),
    ILLUSION("Takes the appearance of the last conscious party Pokebean upon being sent out until hit by a damaging move."),
    IMMUNITY("Prevents the Pokebean from getting poisoned."),
    IMPOSTER("Transforms upon entering battle."),
    INFILTRATOR("Ignores Light Screen, Reflect, and Safeguard."),
    INNER_FOCUS("The Pokebean is protected from flinching."),
    INSOMNIA("Prevents the Pokebean from falling asleep."),
    INTIMIDATE("Lowers the foe’s Attack stat."),
    IRON_BARBS("Damages attacking Pokebean for 1/8 their max HP on contact."),
    IRON_FIST("Boosts the power of punching moves."),
    JUSTIFIED("Raises Attack when hit by dark-type moves."),
    KEEN_EYE("Prevents the Pokebean from losing accuracy."),
    KLUTZ("The Pokebean can’t use any held items."),
    LEAF_GUARD("Prevents status problems in sunny weather."),
    LEVITATE("Gives full immunity to all Ground-type moves."),
    LIGHTNINGROD("The Pokebean draws in all Electric-type moves."),
    LIGHT_METAL("Halves the Pokebean's weight."),
    LIMBER("The Pokebean is protected from paralysis."),
    LIQUID_OOZE("Inflicts damage on foes using any draining move."),
    MAGIC_BOUNCE("Reflects most non-damaging moves back at their user."),
    MAGIC_GUARD("The Pokebean only takes damage from attacks."),
    MAGMA_ARMOR("Prevents the Pokebean from becoming frozen."),
    MAGNET_PULL("Prevents Steel-type Pokebean from escaping."),
    MARVEL_SCALE("Boosts Defense if there is a status problem."),
    MINUS("Boosts Sp. Atk if another Pokebean has Plus."),
    MOLD_BREAKER("Moves can be used regardless of Abilities."),
    MOODY("Raises a random stat two stages and lowers another one stage after each turn."),
    MOTOR_DRIVE("Raises Speed if hit by an Electric-type move."),
    MOXIE("Raises Attack one stage upon KOing a Pokebean."),
    MULTISCALE("Halves damage taken from full HP."),
    MULTITYPE("Changes type to match the held Plate."),
    MUMMY("Contact with this Pokebean spreads this Ability."),
    NATURAL_CURE("All status problems are healed upon switching out."),
    NORMALIZE("All the Pokebean’s moves become the Normal type."),
    NO_GUARD("Ensures the Pokebean and its foe’s attacks land."),
    OBLIVIOUS("Prevents the Pokebean from becoming infatuated."),
    OVERCOAT("Protects against damage from weather."),
    OVERGROW("Powers up Grass-type moves in a pinch."),
    OWN_TEMPO("Prevents the Pokebean from becoming confused."),
    PICKPOCKET("Steals attacking Pokebean's held item on contact."),
    PICKUP("The Pokebean may pick up items."),
    PLUS("Boosts Sp. Atk if another Pokebean has Minus."),
    POISON_HEAL("Restores HP if the Pokebean is poisoned."),
    POISON_POINT("Contact with the Pokebean may poison the foe."),
    POISON_TOUCH("Has a 30% chance of poisoning Pokebean upon contact when attacking."),
    PRANKSTER("Raises non-damaging moves' priority by one stage."),
    PRESSURE("The Pokebean raises the foe’s PP usage."),
    PURE_POWER("Boosts the power of physical attacks."),
    QUICK_FEET("Boosts Speed if there is a status problem."),
    RAIN_DISH("The Pokebean gradually recovers HP in rain."),
    RATTLED("Raises Speed one stage upon being hit by a Dark, Ghost, or Bug move."),
    RECKLESS("Powers up moves that have recoil damage."),
    REGENERATOR("Heals for 1/3 max HP upon leaving battle."),
    RIVALRY("Raises Attack if the foe is of the same gender."),
    ROCK_HEAD("Protects the Pokebean from recoil damage."),
    ROUGH_SKIN("Inflicts damage to the foe on contact."),
    RUN_AWAY("Enables sure getaway from wild Pokebean."),
    SAND_FORCE("Strengthens Rock, Ground, and Steel moves to 1.3× their power during a sandstorm."),
    SAND_RUSH("Doubles Speed during a sandstorm."),
    SAND_STREAM("The Pokebean summons a sandstorm in battle."),
    SAND_VEIL("Boosts the Pokebean’s evasion in a sandstorm."),
    SAP_SIPPER("Absorbs Grass moves, raising Attack one stage."),
    SCRAPPY("Enables moves to hit Ghost-type foes."),
    SERENE_GRACE("Boosts the likelihood of added effects appearing."),
    SHADOW_TAG("Prevents the foe from escaping."),
    SHED_SKIN("The Pokebean may heal its own status problems."),
    SHEER_FORCE("Strengthens moves with extra effects to 1.3× their power, but prevents their extra effects."),
    SHELL_ARMOR("The Pokebean is protected against critical hits."),
    SHIELD_DUST("Blocks the added effects of attacks taken."),
    SIMPLE("The Pokebean is prone to wild stat changes."),
    SKILL_LINK("Increases the frequency of multi-strike moves."),
    SLOW_START("Temporarily halves Attack and Speed."),
    SNIPER("Powers up moves if they become critical hits."),
    SNOW_CLOAK("Raises evasion in a hailstorm."),
    SNOW_WARNING("The Pokebean summons a hailstorm in battle."),
    SOLAR_POWER("Boosts Sp. Atk, but lowers HP in sunshine."),
    SOLID_ROCK("Powers down super-effective moves."),
    SOUNDPROOF("Gives full immunity to all sound-based moves."),
    SPEED_BOOST("The Pokebean’s Speed stat is gradually boosted."),
    STALL("The Pokebean moves after even slower foes."),
    STATIC("Contact with the Pokebean may cause paralysis."),
    STEADFAST("Raises Speed each time the Pokebean flinches."),
    STENCH("The stench helps keep wild Pokebean away."),
    STICKY_HOLD("Protects the Pokebean from item theft."),
    STORM_DRAIN("The Pokebean draws in all Water-type moves."),
    STURDY("The Pokebean is protected against 1-hit KO attacks."),
    SUCTION_CUPS("Negates moves that force switching out."),
    SUPER_LUCK("Heightens the critical-hit ratios of moves."),
    SWARM("Powers up Bug-type moves in a pinch."),
    SWIFT_SWIM("Boosts the Pokebean’s Speed in rain."),
    SYNCHRONIZE("Passes on a burn, poison, or paralysis to the foe."),
    TANGLED_FEET("Raises evasion if the Pokebean is confused."),
    TECHNICIAN("Powers up the Pokebean’s weaker moves."),
    TELEPATHY("Protects against damaging moves from friendly Pokebean."),
    TERAVOLT("Moves can be used regardless of Abilities."),
    THICK_FAT("Raises resistance to Fire- and Ice-type moves."),
    TINTED_LENS("Powers up 'not very effective' moves."),
    TORRENT("Powers up Water-type moves in a pinch."),
    TOXIC_BOOST("Increases Attack to 1.5× when poisoned."),
    TRACE("The Pokebean copies a foe's Ability."),
    TRUANT("The Pokebean can't attack on consecutive turns."),
    TURBOBLAZE("Moves can be used regardless of Abilities."),
    UNAWARE("Ignores any change in stats by the foe."),
    UNBURDEN("Raises Speed if a held item is used."),
    UNNERVE("Prevents opposing Pokebean from eating held Berries."),
    VICTORY_STAR("Raises moves' accuracy to 1.1× for friendly Pokebean."),
    VITAL_SPIRIT("Prevents the Pokebean from falling asleep."),
    VOLT_ABSORB("Restores HP if hit by an Electric-type move."),
    WATER_ABSORB("Restores HP if hit by a Water-type move."),
    WATER_VEIL("Prevents the Pokebean from getting a burn."),
    WEAK_ARMOR("Raises Speed and lowers Defense by one stage each upon being hit by any move."),
    WHITE_SMOKE("Prevents the Pokebean’s stats from being lowered."),
    WONDER_GUARD("Only super effective moves will hit."),
    WONDER_SKIN("Has a 50% chance of protecting against non-damaging moves that inflict major status ailments."),
    ZEN_MODE("Changes the Pokebean's shape when HP is halved.");

    private final String DESCRIPTION;

    Ability(String description)
    {
        DESCRIPTION = description;
    }

    public final String getDescription()
    {
        return DESCRIPTION;
    }
}
